apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    - image: ghcr.io/imperialops/graveyard
deploy:
  helm:
    releases:
      - name: airgap-webhook
        repo: https://imperialops.github.io/helm-charts 
        remoteChart: airgap-webhook
        setValueTemplates:
          admission.image.registry: "{{.IMAGE_DOMAIN_ghcr_io_imperialops_graveyard}}"
          admission.image.repository: "{{.IMAGE_REPO_NO_DOMAIN_ghcr_io_imperialops_graveyard}}"
          admission.image.tag: "{{.IMAGE_TAG_ghcr_io_imperialops_graveyard}}"
          admission.image.digest: "{{.IMAGE_DIGEST_ghcr_io_imperialops_graveyard}}"
